server:
  port: 8090   #default port where the service will be started
  
  
  
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
spring:     
  application:
    name: department-service   #current service name to be used by the eureka server  
  datasource:
      driver-class-name: com.mysql.jdbc.Driver 
      url: jdbc:mysql://localhost:3306/employee
      username: root
      password: Cutie254$
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true
   hibernate:
         ddl-auto: create 
    
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.   
    
logging:
  level:
    com.example.howtodoinjava: DEBUG          